Fix multichar character constant warning
Multi-character character constants are implementation defined, and therefore they are risky to use for use when trying to be compatible with so many different platforms.

```
Core/gb.c: In function ‘GB_is_inited’:
Core/gb.c:423:25: error: multi-character character constant [-Werror=multichar]
     return gb->magic == 'SAME';
                         ^~~~~~
Core/gb.c: In function ‘GB_reset’:
Core/gb.c:560:28: error: multi-character character constant [-Werror=multichar]
     gb->magic = (uintptr_t)'SAME';
                            ^~~~~~
```

This change turns the multi-character into a define with the converted integer.